### ISSUE TITLE
docker-compose upで開発環境を立ち上げられるようにする

### ISSUE THREAD

**Issue by yuiseki** [yuiseki/crisis-news-map-next#1]

**Comment by zonoise** [comment]
こんにちは、docker-compose.yml を書いてみましたが、プルリクを送っても大丈夫ですか？

**Comment by yuiseki** [comment]
是非お願いします…！！

**Comment by zonoise** [comment]
@yuiseki 
こちらになります。
https://github.com/yuiseki/crisis-news-map-next/pull/20#issue-683412113

**Comment by yuiseki** [comment]
closed by #20
