### ISSUE TITLE
タイの誤判定が多すぎる

### ISSUE THREAD

**Issue by yuiseki** [yuiseki/crisis-news-map-next#2]
以下の単語を含むニュースの位置情報がタイと誤判定されてしまっている

- タイプ
- タイミング
- タイトル
- セミリタイア
- パートタイム
- フルタイム

**Comment by pastak** [comment]
実装見てないのですが、雑に考えると`タイ`の前後両方にカタカナが無いということを見るとか？（他の地名もニュースの文脈で前後両方にカタカナがくっつくのは直感ではあまり無さそうなので一般化しても良いかも？

**Comment by hata6502** [comment]
https://github.com/yuiseki/crisis-news-map-next/blob/main/src/lib/detector.ts#L206
https://github.com/yuiseki/crisis-news-map-next/blob/main/src/data/geonlp.ex.nii.ac.jp/geonlp_world_country_20130912_u.csv

`detectCountry()` 読んでます。

**Comment by hata6502** [comment]
`kuromojin` という npm パッケージ使うと形態素解析できますが、
ちょっと大がかりな感じ……

https://takuyaa.github.io/kuromoji.js/demo/tokenize.html

[![Image from Gyazo](https://i.gyazo.com/6a4d1ea4461b74e3c90a4e616afba2a3.png)](https://gyazo.com/6a4d1ea4461b74e3c90a4e616afba2a3)
