### ISSUE TITLE
日本の災害関連ニュース記事で「すべて」のラジオボタンがチェック状態にならない

### ISSUE THREAD

**Issue by yamanoku** [yuiseki/crisis-news-map-next#21]
本番環境にて確認

https://crisis.yuiseki.net/place/%E6%97%A5%E6%9C%AC/
<img width="1049" alt="Screen Shot 2021-07-11 at 12 25 17" src="https://user-images.githubusercontent.com/1996642/125181769-29636c80-e243-11eb-96c2-43a81fd8c2f7.png">

https://crisis.yuiseki.net/place/%E6%97%A5%E6%9C%AC/?category=crisis
<img width="1049" alt="Screen Shot 2021-07-11 at 12 25 23" src="https://user-images.githubusercontent.com/1996642/125181783-3ed89680-e243-11eb-9ad0-5b578a9e9ed7.png">

---

https://github.com/yuiseki/crisis-news-map-next/blob/main/src/components/LocalNewsPage.tsx#L94 の箇所で
「すべて」選択時に条件が一致すればよさそうです。

**Comment by yuiseki** [comment]
issue作成ありがとうございました。自分でも気になっていた所だったので修正しました。
